// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: log.sql

package database

import (
	"context"

	utils "github.com/ScMofeoluwa/ingestor/internal/utils"
)

const createLog = `-- name: CreateLog :exec
INSERT INTO "logs" ("data") VALUES ($1)
`

func (q *Queries) CreateLog(ctx context.Context, data utils.LogEntry) error {
	_, err := q.db.Exec(ctx, createLog, data)
	return err
}
