// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	utils "github.com/ScMofeoluwa/ingestor/internal/utils"
	"github.com/google/uuid"
)

type Log struct {
	ID   uuid.UUID      `json:"id"`
	Data utils.LogEntry `json:"data"`
}
