// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"

	utils "github.com/ScMofeoluwa/ingestor/internal/utils"
)

type Querier interface {
	CreateLog(ctx context.Context, data utils.LogEntry) error
}

var _ Querier = (*Queries)(nil)
